version: 2.1

jobs:
  build:
    docker:
      - image: hashicorp/terraform:1.0.4

    working_directory: ~/terraform

    steps:
      - checkout

      # Install any dependencies needed for your Terraform code
      # - run:
      #     name: Install Dependencies
      #     command: |
      #       apt-get update && apt-get install -y <your-package>

      - run:
          name: Terraform Init
          command: terraform init

      - run:
          name: Terraform Plan
          command: terraform plan -out=tfplan

      - hold_approval:
          requires:
            - deploy
          filters:
            branches:
              only:
                - main
          steps:
            - run:
                name: Wait for Approval
                command: |
                  if [ "${APPROVAL_STATUS}" != "approved" ]; then
                    echo "Deployment not approved. Exiting..."
                    exit 1
                  fi
            
      - run:
          name: Terraform Apply
          command: terraform apply -auto-approve tfplan

workflows:
  version: 2
  build:
    jobs:
      - build
