version: 2.1
 
jobs:
  build:
    docker:
      - image: hashicorp/terraform:1.0.4
 
    working_directory: ~/terraform
 
    steps:
      - checkout
 
      # Install any dependencies needed for your Terraform code
      # - run:
      #     name: Install Dependencies
      #     command: |
      #       apt-get update && apt-get install -y <your-package>
 
      - run:
          name: Terraform Init
          command: terraform init
 
      - run:
          name: Terraform Plan
          command: terraform plan -out=tfplan
      
 
  manual_approval:
    docker:
      - image: circleci/classic:202103-01
 
    steps:
      - run:
          name: Manual Approval
          command: echo "Please manually approve this deployment."  
 
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
 
      - manual_approval:
          type: approval
          requires:
            - build
          filters:
            branches:
              only:
                - main

      - run:
         name: Terraform Apply
         command: terraform apply -auto-approve tfplan 
