version: 2.1
 
jobs:
  build:
    docker:
      - image: hashicorp/terraform:1.0.4
    working_directory: ~/terraform
 
    steps:
      - run:
          name: Build
          command: mvn verify
            # Your build commands here
 
   deploy:
     docker:
       - image: hashicorp/terraform:1.0.4
 
    steps:
      - run:
          name: Deploy
          command: mvn verify
            # Your deployment commands here
 
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
 
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - main
 
      - hold_approval:
          requires:
            - deploy
          filters:
            branches:
              only:
                - main
          steps:
            - run:
                name: Wait for Approval
                command: |
                  if [ "${APPROVAL_STATUS}" != "approved" ]; then
                    echo "Deployment not approved. Exiting..."
                    exit 1
                  fi
