version: 2.1

jobs:
  build:
    docker:
      - image: hashicorp/terraform:1.0.4

    working_directory: ~/terraform

    steps:
      - checkout

      - run:
          name: Terraform Init
          command: terraform init

      - run:
          name: Terraform Plan
          command: terraform plan -out=tfplan

      - persist_to_workspace:
          root: .
          paths:
            - tfplan

  apply:
    docker:
      - image: hashicorp/terraform:1.0.4

    working_directory: ~/terraform

    steps:
      - attach_workspace:
          at: ~/terraform

      - run:
          name: Terraform Apply
          command: terraform apply -auto-approve tfplan

workflows:
  version: 2
  build_and_apply:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - apply:
          requires:
            - build
          filters:
            branches:
              only:
                - main
