version: 2.1

jobs:
  build:
    docker:
      - image: hashicorp/terraform:1.0.4

    working_directory: ~/terraform

    steps:
      - checkout

      - run:
          name: Terraform Init
          command: terraform init

      - run:
          name: Terraform Plan
          command: terraform plan -out=tfplan

      - persist_to_workspace:
          root: .
          paths:
            - tfplan

  approve:
    docker:
      - image: cimg/base:2021.09

    working_directory: ~/terraform

    steps:
      - attach_workspace:
          at: ~/terraform

      # Display the Terraform plan for review
      - run:
          name: Display Terraform Plan
          command: terraform show tfplan

      # Use the `hold` command to pause and wait for user approval
      - hold:
          type: approval
          reason: "Manual approval required before Terraform apply."

  apply:
    docker:
      - image: hashicorp/terraform:1.0.4

    working_directory: ~/terraform

    steps:
      - attach_workspace:
          at: ~/terraform

      - run:
          name: Terraform Apply
          command: terraform apply -auto-approve tfplan

workflows:
  version: 2
  build_and_apply:
    jobs:
      - build
      - approve:
          requires:
            - build
      - apply:
